version: "3.3"

services:
  postgresql:
    image: "postgres:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airflow_db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: 1234
